services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: always
    container_name: ${KEYCLOAK_HOSTNAME}
    command: start --proxy-headers forwarded --import-realm
    ports:
      - "${KEYCLOAK_HTTP_PORT}:${KEYCLOAK_HTTP_PORT}"
    user: 1000:1000 # default 1000 user, 0 group
    environment:
      KC_HTTP_PORT: ${KEYCLOAK_HTTP_PORT}
      KC_DB: mysql
      KC_DB_URL_HOST: mysql_svr
      KC_DB_URL_DATABASE: ${KEYCLOAK_DATABASE}
      KC_DB_PASSWORD: ${KEYCLOAK_MYSQL_PASSWORD}
      KC_DB_USERNAME: ${KEYCLOAK_MYSQL_USER}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      # Production
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/certs/keycloak.key.pem
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/certs/keycloak.crt.pem
    depends_on:
      mysql_svr:
        condition: service_healthy
    volumes:
      - ./keycloak/certs/:/opt/keycloak/certs/
      - ./keycloak/realm-data:/opt/keycloak/data/import
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2048M
        reservations:
          cpus: "1"
          memory: 2048M
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    security_opt:
      - no-new-privileges:true
    networks:
      - private-subnet
      - data-subnet

  mysql_svr:
    image: mysql:latest
    restart: always
    container_name: mysql_svr
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./backend/mysql/db:/var/lib/mysql
      - ./backend/mysql/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u ${KEYCLOAK_DATABASE} --password=${KEYCLOAK_MYSQL_PASSWORD}
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2048M
        reservations:
          cpus: "0.5"
          memory: 1024M
    networks:
      - data-subnet

networks:
  public-subnet:
    driver: bridge
  private-subnet:
    driver: bridge
  data-subnet:
    driver: bridge
